
### 优惠券全量生成
POST http://localhost:8080/hapcode/coding
Content-Type: application/json

{
  "tableNames":["sys_company","sys_user","sys_supplier"],
  "templateNames":[
    "model.java.btl"
  ]
}



### 优惠券全量生成
POST http://localhost:8080/hapcode/coding
Content-Type: application/json

{
  "tableNames":["company_customer"],
  "templateNames":[
    "model.java.btl",
    "modelInsertDTO.java.btl",
    "modelUpdateDTO.java.btl",
    "modelListDTO.java.btl",
    "modelController.java.btl",
    "modelVO.java.btl",
    "modelClient.java.btl",
    "modelClientFallbackFactory.java.btl",
    "ImodelService.java.btl",
    "modelServiceImpl.java.btl",
    "modelMapper.java.btl",
    "modelMapper.xml.btl"
  ]
}


### 优惠券生成VO ,"sys_user","sys_supplier"
POST http://localhost:8080/hapcode/coding
Content-Type: application/json

{
  "tableNames":["sys_company"],
  "templateNames":[
    "modelMapper.xml.btl"
  ]
}

###

