spring:
  application:
    name: hapcode-premium
  datasource:
    url: jdbc:mysql://localhost:3306/item?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

base-content:
  root-path: D:\workspace\aiwoplatformat\sys-base\user-manage-server\src\main\java\
model:
  package-name: com.jbs.usermanage.model
  imports:
    - java.util.List
    - java.util.Map




