spring:
  application:
    name: hapcode-premium
  datasource:
    url: jdbc:mysql://localhost:3306/item?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

base-content:
  root-path: D:\workspace\aiwoplatformat\beauty-business\item-business-server\src\main\
  author: wuyulin
  namespace-prefix: com.jbs.item

model:
  package-name: com.jbs.item.model
  file-type: java

model-dto:
  root-path: D:\workspace\aiwoplatformat\beauty-business\item-business-client\src\main\
  package-name: com.jbs.item.dto
  file-type: java
  imports:

model-client:
  root-path: D:\workspace\aiwoplatformat\beauty-business\item-business-client\src\main\
  package-name: com.jbs.item.client
  file-type: java
  feign-client-server: item-server
  imports:
    - com.jbs.common.output.Result

model-client-fallback-factory:
  root-path: D:\workspace\aiwoplatformat\beauty-business\item-business-client\src\main\
  package-name: com.jbs.item.factory
  file-type: java
  imports:
    - com.jbs.common.output.Result

model-controller:
  package-name: com.jbs.item.web
  file-type: java
  imports:
    - com.jbs.common.output.Result

model-service:
  package-name: com.jbs.item.service
  file-type: java
  imports:

model-service-impl:
  package-name: com.jbs.item.service.impl
  file-type: java
  imports:

model-mapper:
  package-name: com.jbs.item.mapper
  file-type: java
  imports:

model-mapper-xml:
  package-name: mapper
  file-type: resources
  imports:
    - java.util.List
    - java.util.Map
