spring:
  application:
    name: hapcode-premium
  datasource:
    url: jdbc:mysql://47.111.228.201:23306/aiwo_plat_user?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: jbs-aiwo

base-content:
  root-path: D:\20210406\ideaSpace\aiwo-plat-user\aiwo-plat-user-app\src\main\
  author: wuyulin
  namespace-prefix: com.jbs.aiwoplatuser

model:
  package-name: com.jbs.aiwoplatuser.app.model
  file-type: java

model-insert-dto:
  root-path: D:\20210406\ideaSpace\aiwo-plat-user\aiwo-plat-user-client\src\main\
  package-name: com.jbs.aiwoplatuser.dto
  file-type: java


model-update-dto:
  root-path: D:\20210406\ideaSpace\aiwo-plat-user\aiwo-plat-user-client\src\main\
  package-name: com.jbs.aiwoplatuser.dto
  file-type: java


model-list-dto:
  root-path: D:\20210406\ideaSpace\aiwo-plat-user\aiwo-plat-user-client\src\main\
  package-name: com.jbs.aiwoplatuser.dto
  file-type: java


model-vo:
  root-path: D:\20210406\ideaSpace\aiwo-plat-user\aiwo-plat-user-client\src\main\
  package-name: com.jbs.aiwoplatuser.vo
  file-type: java
  imports:

model-client:
  root-path: D:\20210406\ideaSpace\aiwo-plat-user\aiwo-plat-user-client\src\main\
  package-name: com.jbs.aiwoplatuser.client
  file-type: java
  feign-client-server: aiwo-plat-user
  imports:
    - com.jbs.aiwocommon.vo.Result

model-client-fallback-factory:
  root-path: D:\20210406\ideaSpace\aiwo-plat-user\aiwo-plat-user-client\src\main\
  package-name: com.jbs.aiwoplatuser.factory
  file-type: java
  imports:
    - com.jbs.aiwocommon.vo.Result

model-controller:
  root-path: D:\20210406\ideaSpace\aiwo-plat-user\aiwo-plat-user-adapter\src\main\
  package-name: com.jbs.aiwoplatuser.adapter.controller
  file-type: java
  imports:
    - com.jbs.aiwocommon.vo.Result
    - io.swagger.annotations.Api
    - io.swagger.annotations.ApiOperation


model-service:
  package-name: com.jbs.aiwoplatuser.app.service
  file-type: java
  imports:

model-service-impl:
  package-name: com.jbs.aiwoplatuser.app.service.impl
  file-type: java
  imports:

model-mapper:
  package-name: com.jbs.aiwoplatuser.app.mapper
  file-type: java
  imports:

model-mapper-xml:
  package-name: mapper
  file-type: resources