spring:
  application:
    name: hapcode-premium
  datasource:
    url: jdbc:mysql://localhost:3306/item?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

base-content:
  root-path: D:\workspace\aiwoplatformat\beauty-business\item-business-server\src\main\
  author: wuyulin

model:
  package-name: com.jbs.item.model
  file-type: java

dto:
  root-path: D:\workspace\aiwoplatformat\beauty-business\item-business-client\src\main\
  package-name: com.jbs.item.dto
  file-type: java
  imports:
    - java.util.List
    - java.util.Map

controller:
  package-name: mapper
  file-type: java
  imports:
    - java.util.List
    - java.util.Map

iservice:
  package-name: com.jbs.item.service
  file-type: java
  imports:
    - java.util.List
    - java.util.Map

service-impl:
  package-name: com.jbs.item.service.impl
  file-type: java
  imports:
    - java.util.List
    - java.util.Map

dao-java:
  package-name: com.jbs.item.dto
  file-type: java
  imports:
    - java.util.List
    - java.util.Map

dao-xml:
  package-name: mapper
  file-type: resources
  imports:
    - java.util.List
    - java.util.Map
