spring:
  application:
    name: hapcode-premium
  datasource:
    url: jdbc:mysql://localhost:3306/item?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

base-content:
  root-path: D:\workspace\aiwoplatformat\beauty-business\item-business-server\src\main\
  author: wuyulin
  namespace-prefix: com.jbs.item

model:
  package-name: com.jbs.item.model
  file-type: java

model-dto:
  root-path: D:\workspace\aiwoplatformat\beauty-business\item-business-client\src\main\
  package-name: com.jbs.item.dto
  file-type: java
  imports:
    - import com.jbs.common.output.Result

model-controller:
  package-name: com.jbs.item.controller
  file-type: java
  imports:

model-service:
  package-name: com.jbs.item.service
  file-type: java
  imports:

model-service-impl:
  package-name: com.jbs.item.service.impl
  file-type: java
  imports:

model-mapper:
  package-name: com.jbs.item.mapper
  file-type: java
  imports:
    - import java.util.List
    - import java.util.Map

model-mapper-xml:
  package-name: mapper
  file-type: resources
  imports:
    - java.util.List
    - java.util.Map
