server:
  port: 8080
spring:
  application:
    name: my-code-generator
  datasource:
    url: jdbc:mysql://192.168.18.86:3306/erp_product?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456